#!/bin/bash

# config
APP=agent
NODE_NAME=${APP}
RUNAPP=${APP}_app
CTLAPP=${APP}_ctl
CITYID=common

#define default configuration
POLL=true
SMP=disable
ERL=erl
ERL_MAX_PORTS=32000
ERL_PROCESSES=25000
ERL_MAX_ETS_TABLES=1400
ROOTDIR=`cd $(dirname $0); pwd`
EBIN=$ROOTDIR/ebin
ERL_LIBS=../lib


ARGS=

while [ $# -ne 0 ] ;
do
    PARAM=$1

    shift

    case $PARAM in

	--) break;;

	--app) APP=$1; RUNAPP=${APP}_app; CTLAPP=${APP}_ctl; shift;;

	--name) NODE_NAME=$1; shift;;

	--db_node) DB_NODE=$1; shift;;

	--cityid) CITYID=$1; shift;;

	*) ARGS="$ARGS $PARAM" ;;

    esac

done


# define environment variables
OPENGOSS_DB="$ROOTDIR/var/data/$NODE_NAME"
OPENGOSS_CONFIG_PATH="$ROOTDIR/etc/$APP"
OPENGOSS_LOG="$ROOTDIR/log"
SASL_LOG_PATH="$ROOTDIR/log/${NODE_NAME}_sasl.log"
NODE_LOG_PATH="$ROOTDIR/log/${NODE_NAME}.log"


# export global variables
export OPENGOSS_SO_PATH
export ERL_MAX_PORTS
export ERL_MAX_ETS_TABLES
export ERL_LIBS

DETACHED="-noinput -detached"
ERLANG_OPTS="-smp $SMP +P $ERL_PROCESSES +K $POLL "
#DETACHED=""

[ -d $OPENGOSS_DB ] || mkdir -p $OPENGOSS_DB
[ -d $OPENGOSS_LOG ] || mkdir -p $OPENGOSS_LOG


#start server

#$DETACHED \
start()
{
    $ERL $ERLANG_OPTS \
		$DETACHED \
        -sname  $NODE_NAME \
      	-pa $EBIN \
	-setcookie public \
	-config $OPENGOSS_CONFIG_PATH \
    -sasl sasl_error_logger \{file,\"$SASL_LOG_PATH\"\} \
	-lager handlers \[\{lager_console_backend,info\},\{\lager_file_backend,\[\{\"$NODE_LOG_PATH\",info,20485760,\"\$D0\",5\}\]}\] \
	-boot start_sasl \
	-cityid $CITYID \
	-setcookie public \
	-s reloader start -s $RUNAPP start
}

console()
{
    $ERL $ERLANG_OPTS \
        -sname  $NODE_NAME \
		-setcookie public \
      	-pa $EBIN \
	-config $OPENGOSS_CONFIG_PATH \
    -sasl sasl_error_logger \{file,\"$SASL_LOG_PATH\"\} \
	-lager handlers \[\{lager_console_backend,info\},\{\lager_file_backend,\[\{\"$NODE_LOG_PATH\",info,20485760,\"\$D0\",5\}\]}\] \
	-boot start_sasl \
	-cityid $CITYID \
	-s reloader start -s $RUNAPP start
}

stop()
{
    $ERL \
	-noinput \
	-sname $CTLAPP \
	-setcookie public \
    -pa $EBIN \
	-s $CTLAPP -extra $NODE_NAME stop
    result=$?
    case $result in
    0) echo "Success";;
    *) echo "Failure";;
    esac
}

ctl ()
{
    $ERL \
    -sname $CTLAPP \
	-setcookie public \
    -noinput \
    -boot start_clean \
    -pa $EBIN \
    -s ${CTLAPP} -extra $NODE_NAME $@
    result=$?
    case $result in
    0) echo "Success";;
    *) echo "Failure";;
    esac
    return $result
}


case $ARGS in
	' start') start;;
	' stop') stop;;
	' console') console;;
	*) ctl $ARGS;;
esac

